name: Update Credly Badges

on:
  schedule:
    # 매일 자정에 자동으로 실행 (UTC 기준)
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Badges - Readme
        uses: pemtajo/badge-readme@3.2
        with:
          CREDLY_USER: 'kyeonghwan-son'

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add README.md
          # 변경 사항이 있을 때만 커밋하고 푸시
          git diff-index --quiet HEAD || git commit -m "Update Credly badges"
          git push
