name: Update Credly Badges
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # ← 이 줄 추가
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Badges - Readme
        uses: pemtajo/badge-readme@3.2
        with:
          CREDLY_USER: 'kyeonghwan-son'
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff-index --quiet HEAD || git commit -m "Update Credly badges"
          git push
